"""Seed database with a demo artist for testing and demos.

Creates:
- 1 Tenant ("Seed Studio")
- 1 User (demo@amplify.local)
- 1 Membership (owner)
- 1 Artist ("The Velvet Hooks" — indie rock)
- 1 Release (album "Paper Thin Walls" with 10 tracks, releasing 2026-05-02)
- 3 ChannelConnections (Instagram, TikTok, YouTube — no real tokens)
- 1 Campaign ("Paper Thin Walls Launch" — pre_release phase, PENDING workflow)
- Pre-release calendar items (4 weeks generated by PreReleaseWorkflow)
- Release-day checklist
- 2 Posts (1 draft, 1 scheduled)
- 1 Approval (pending)
- 1 Experiment (A/B hook style)
- 1 BillingPlan (solo tier)
- 1 Subscription

Usage:
    python scripts/seed_artist.py

Requires DATABASE_URL environment variable or uses docker-compose default.
"""

from __future__ import annotations

import asyncio
import os
import uuid
from datetime import date, datetime, time, timedelta, timezone

try:
    from sqlalchemy import select
    from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker
except ImportError:
    print("ERROR: SQLAlchemy is not installed.")
    print("  pip install sqlalchemy[asyncio] asyncpg")
    raise SystemExit(1)

from amplify.db.base import Base
from amplify.db.models import (
    ApprovalModel,
    ArtistModel,
    AuditLogModel,
    BillingPlanModel,
    CalendarItemModel,
    CampaignModel,
    ChannelConnectionModel,
    ExperimentModel,
    MembershipModel,
    PostModel,
    ReleaseModel,
    SubscriptionModel,
    TenantModel,
    TrackModel,
    UserModel,
)
from amplify.core.workflows.pre_release import PreReleaseWorkflow
from amplify.core.workflows.release_day import ReleaseDayWorkflow
from amplify.core.workflows.post_release_30 import PostRelease30Workflow

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql+asyncpg://amplify:amplify@localhost:5432/amplify_os",
)

# ── Fixed IDs ────────────────────────────────────────────────────────
TENANT_ID = uuid.UUID("aaaaaaaa-0000-0000-0000-000000000001")
USER_ID = uuid.UUID("aaaaaaaa-0000-0000-0000-000000000002")
ARTIST_ID = uuid.UUID("aaaaaaaa-0000-0000-0000-000000000003")
RELEASE_ID = uuid.UUID("aaaaaaaa-0000-0000-0000-000000000004")
CAMPAIGN_ID = uuid.UUID("aaaaaaaa-0000-0000-0000-000000000005")
PLAN_ID = uuid.UUID("aaaaaaaa-0000-0000-0000-000000000006")

CH_IG_ID = uuid.UUID("aaaaaaaa-0000-0000-0000-0000000000C1")
CH_TT_ID = uuid.UUID("aaaaaaaa-0000-0000-0000-0000000000C2")
CH_YT_ID = uuid.UUID("aaaaaaaa-0000-0000-0000-0000000000C3")

RELEASE_DATE = date(2026, 5, 2)
CAMPAIGN_START = RELEASE_DATE - timedelta(weeks=4)
CAMPAIGN_END = RELEASE_DATE + timedelta(days=30)
CHANNELS = ["instagram", "tiktok", "youtube"]


def _now() -> datetime:
    return datetime.now(timezone.utc)


async def seed() -> None:
    """Seed demo artist with a pending album release workflow."""
    engine = create_async_engine(DATABASE_URL, echo=False)
    factory = async_sessionmaker(
        bind=engine, class_=AsyncSession, expire_on_commit=False
    )

    async with factory() as session:
        # --- Idempotency ---
        result = await session.execute(
            select(TenantModel).where(TenantModel.slug == "seed-artist")
        )
        if result.scalar_one_or_none() is not None:
            print("Seed data already exists (tenant 'seed-artist' found). Skipping.")
            await engine.dispose()
            return

        now = _now()

        # ── 1. Tenant ────────────────────────────────────────────
        session.add(TenantModel(
            id=TENANT_ID,
            name="Seed Studio",
            slug="seed-artist",
            plan_tier="solo",
            settings={"timezone": "America/Los_Angeles", "brand_color": "#E74C3C"},
            is_active=True,
        ))
        print(f"  Tenant: {TENANT_ID} (Seed Studio)")

        # ── 2. User ──────────────────────────────────────────────
        session.add(UserModel(
            id=USER_ID,
            email="demo@amplify.local",
            hashed_password="$2b$12$demo_seed_not_real",
            display_name="Demo User",
            is_active=True,
        ))
        print(f"  User: {USER_ID} (demo@amplify.local)")

        # ── 3. Membership ────────────────────────────────────────
        session.add(MembershipModel(
            id=uuid.uuid4(),
            user_id=USER_ID,
            tenant_id=TENANT_ID,
            role="owner",
        ))

        # ── 4. Artist ────────────────────────────────────────────
        session.add(ArtistModel(
            id=ARTIST_ID,
            tenant_id=TENANT_ID,
            name="The Velvet Hooks",
            slug="the-velvet-hooks",
            bio=(
                "The Velvet Hooks are a four-piece indie rock band from Portland, OR. "
                "Their sound blends jangly guitars with synth textures and lyrics about "
                "city life, late-night diners, and the feeling of almost remembering a dream."
            ),
            genre="Indie Rock",
            image_url=None,
            spotify_id=None,
            social_links={
                "instagram": "https://instagram.com/thevelvethooks",
                "tiktok": "https://tiktok.com/@velvethooks",
                "youtube": "https://youtube.com/@thevelvethooks",
            },
        ))
        print(f"  Artist: {ARTIST_ID} (The Velvet Hooks)")

        # ── 5. Release ───────────────────────────────────────────
        session.add(ReleaseModel(
            id=RELEASE_ID,
            tenant_id=TENANT_ID,
            artist_id=ARTIST_ID,
            title="Paper Thin Walls",
            release_type="album",
            status="scheduled",
            release_date=RELEASE_DATE,
            upc="196588999901",
            artwork_url=None,
            metadata_={
                "label": "Self-Released",
                "genre_tags": ["indie rock", "alternative", "dream pop"],
                "distributor": "DistroKid",
            },
        ))
        print(f"  Release: {RELEASE_ID} (Paper Thin Walls — {RELEASE_DATE})")

        # ── 5b. Tracks (10 tracks) ──────────────────────────────
        tracks = [
            ("Paper Thin Walls", 1, 218, "QZDEM2600001", True),
            ("Neon Diner", 2, 245, "QZDEM2600002", False),
            ("Almost Remembered", 3, 312, "QZDEM2600003", True),
            ("Sidewalk Cracks", 4, 189, "QZDEM2600004", False),
            ("Rooftop Frequency", 5, 267, "QZDEM2600005", False),
            ("Borrowed Light", 6, 234, "QZDEM2600006", False),
            ("The Getaway Van", 7, 198, "QZDEM2600007", False),
            ("Sugar & Kerosene", 8, 276, "QZDEM2600008", False),
            ("Phantom Limbs", 9, 301, "QZDEM2600009", False),
            ("Last Call", 10, 342, "QZDEM2600010", False),
        ]
        for title, num, dur, isrc, is_single in tracks:
            session.add(TrackModel(
                id=uuid.uuid4(),
                tenant_id=TENANT_ID,
                release_id=RELEASE_ID,
                title=title,
                track_number=num,
                duration_seconds=dur,
                isrc=isrc,
                is_single=is_single,
            ))
            print(f"    Track {num:2d}: {title} ({dur}s)")

        # ── 6. Channel connections ───────────────────────────────
        channels = [
            (CH_IG_ID, "instagram", "thevelvethooks", "The Velvet Hooks"),
            (CH_TT_ID, "tiktok", "velvethooks", "The Velvet Hooks"),
            (CH_YT_ID, "youtube", "UCx_velvethooks", "The Velvet Hooks"),
        ]
        for ch_id, platform, acct_id, display in channels:
            session.add(ChannelConnectionModel(
                id=ch_id,
                tenant_id=TENANT_ID,
                artist_id=ARTIST_ID,
                platform=platform,
                platform_account_id=acct_id,
                display_name=display,
                access_token="seed_token_not_real",
                refresh_token="seed_refresh_not_real",
                token_expires_at=now + timedelta(days=60),
                is_active=True,
                settings={},
            ))
            print(f"  Channel: {platform} ({display})")

        # ── 7. Campaign ─────────────────────────────────────────
        session.add(CampaignModel(
            id=CAMPAIGN_ID,
            tenant_id=TENANT_ID,
            artist_id=ARTIST_ID,
            release_id=RELEASE_ID,
            name="Paper Thin Walls Launch",
            status="active",
            phase="pre_release",
            start_date=CAMPAIGN_START,
            end_date=CAMPAIGN_END,
            budget=1500.00,
            goals={
                "target_streams_first_week": 25000,
                "target_playlist_adds": 15,
                "target_follower_growth": 1000,
            },
            config={
                "platforms": CHANNELS,
                "posting_cadence": "daily",
            },
        ))
        print(f"  Campaign: {CAMPAIGN_ID} (Paper Thin Walls Launch)")

        # ── 8. Calendar — generated from workflow engines ────────
        #
        # Pre-release (4 weeks)
        pre_release_cal = PreReleaseWorkflow.generate_calendar(RELEASE_DATE, CHANNELS)
        cal_count = 0
        for entry in pre_release_cal:
            session.add(CalendarItemModel(
                id=uuid.uuid4(),
                tenant_id=TENANT_ID,
                campaign_id=CAMPAIGN_ID,
                title=f"Week {entry['week']}: {entry['name']}",
                description="; ".join(str(a) for a in entry["actions"]),
                item_type="milestone",
                scheduled_date=date.fromisoformat(str(entry["start_date"])),
                scheduled_time=time(10, 0),
                is_completed=False,
            ))
            cal_count += 1

        # Release day (10 timed actions)
        release_day_cal = ReleaseDayWorkflow.generate_calendar(RELEASE_DATE, CHANNELS)
        for action in release_day_cal:
            hour_str = str(action.get("time", "10:00"))
            hour = int(hour_str.split(":")[0])
            minute = int(hour_str.split(":")[1]) if ":" in hour_str else 0
            session.add(CalendarItemModel(
                id=uuid.uuid4(),
                tenant_id=TENANT_ID,
                campaign_id=CAMPAIGN_ID,
                title=str(action["action"]),
                description=f"Priority: {action.get('priority', 'medium')}",
                item_type="release",
                scheduled_date=RELEASE_DATE,
                scheduled_time=time(hour, minute),
                is_completed=False,
            ))
            cal_count += 1

        # Post-release 30-day (4 weeks)
        post_release_cal = PostRelease30Workflow.generate_calendar(RELEASE_DATE, CHANNELS)
        for entry in post_release_cal:
            session.add(CalendarItemModel(
                id=uuid.uuid4(),
                tenant_id=TENANT_ID,
                campaign_id=CAMPAIGN_ID,
                title=f"Post-Release Week {entry['week']}: {entry['name']}",
                description="; ".join(str(a) for a in entry["actions"]),
                item_type="milestone",
                scheduled_date=date.fromisoformat(str(entry["start_date"])),
                scheduled_time=time(10, 0),
                is_completed=False,
            ))
            cal_count += 1

        print(f"  Calendar: {cal_count} items (pre-release + release day + post-release)")

        # ── 9. Posts (1 draft, 1 scheduled) ──────────────────────
        post_ig_id = uuid.uuid4()
        post_tt_id = uuid.uuid4()

        session.add(PostModel(
            id=post_ig_id,
            tenant_id=TENANT_ID,
            campaign_id=CAMPAIGN_ID,
            channel_id=CH_IG_ID,
            platform="instagram",
            status="draft",
            content_text=(
                "The walls are thin enough to hear the music now. "
                "05.02.26\n\n"
                "#PaperThinWalls #TheVelvetHooks #NewAlbum #IndieRock"
            ),
            media_urls=[],
        ))

        session.add(PostModel(
            id=post_tt_id,
            tenant_id=TENANT_ID,
            campaign_id=CAMPAIGN_ID,
            channel_id=CH_TT_ID,
            platform="tiktok",
            status="scheduled",
            content_text=(
                "POV: your neighbors finally have good taste "
                "#PaperThinWalls #indierock #newmusic"
            ),
            media_urls=[],
            scheduled_at=datetime(2026, 4, 20, 18, 0, 0, tzinfo=timezone.utc),
        ))
        print("  Posts: 1 draft (Instagram), 1 scheduled (TikTok)")

        # ── 10. Approval (pending) ───────────────────────────────
        session.add(ApprovalModel(
            id=uuid.uuid4(),
            tenant_id=TENANT_ID,
            post_id=post_ig_id,
            asset_id=None,
            requested_by=USER_ID,
            reviewed_by=None,
            status="pending",
            notes="Review copy for the teaser post before going live.",
        ))
        print("  Approval: 1 pending")

        # ── 11. Experiment ───────────────────────────────────────
        session.add(ExperimentModel(
            id=uuid.uuid4(),
            tenant_id=TENANT_ID,
            campaign_id=CAMPAIGN_ID,
            name="Teaser Style A/B — Mystery vs. Direct",
            hypothesis=(
                "Mysterious teaser captions ('The walls are thin enough...') will "
                "outperform direct announcements ('New album out May 2') on Instagram "
                "and TikTok engagement."
            ),
            status="draft",
            variants=[
                {
                    "id": 0,
                    "label": "Mystery",
                    "caption": "The walls are thin enough to hear the music now. 05.02.26",
                },
                {
                    "id": 1,
                    "label": "Direct",
                    "caption": "Our new album 'Paper Thin Walls' drops May 2! 10 tracks of indie rock.",
                },
            ],
            metrics_config={
                "primary_metric": "engagement_rate",
                "secondary_metrics": ["saves", "shares"],
                "min_sample_size": 300,
            },
        ))
        print("  Experiment: Teaser Style A/B")

        # ── 12. Billing ──────────────────────────────────────────
        session.add(BillingPlanModel(
            id=PLAN_ID,
            name="Solo",
            tier="solo",
            price_monthly=0.0,
            price_yearly=0.0,
            features=["1 artist", "3 channels", "10 posts/month"],
            limits={
                "max_artists": 1,
                "max_channels": 3,
                "max_posts_per_month": 10,
            },
            is_active=True,
        ))

        session.add(SubscriptionModel(
            id=uuid.uuid4(),
            tenant_id=TENANT_ID,
            plan_id=PLAN_ID,
            status="active",
            current_period_start=date(2026, 4, 1),
            current_period_end=date(2026, 5, 1),
        ))
        print("  Billing: Solo plan")

        # ── 13. Audit log ────────────────────────────────────────
        session.add(AuditLogModel(
            id=uuid.uuid4(),
            tenant_id=TENANT_ID,
            user_id=USER_ID,
            action="campaign.created",
            entity_type="campaign",
            entity_id=CAMPAIGN_ID,
            changes={
                "name": "Paper Thin Walls Launch",
                "status": "active",
                "release_date": RELEASE_DATE.isoformat(),
            },
            ip_address="127.0.0.1",
        ))

        # ── Commit ───────────────────────────────────────────────
        await session.commit()
        print(f"\nSeed complete.")
        print(f"  Artist:       The Velvet Hooks")
        print(f"  Album:        Paper Thin Walls (10 tracks)")
        print(f"  Release date: {RELEASE_DATE}")
        print(f"  Campaign:     pre_release phase, {cal_count} calendar items")
        print(f"  Workflow:     pre-release → release day → post-release 30")

    await engine.dispose()


if __name__ == "__main__":
    print("=" * 60)
    print("  Amplify-OS — Seed Artist Demo Tenant")
    print("  The Velvet Hooks · Paper Thin Walls · 2026-05-02")
    print("=" * 60)
    print()
    asyncio.run(seed())
