"""add_oauth_columns_to_channel_connections

Revision ID: 231c11451996
Revises: b7c9d3e2f158
Create Date: 2026-03-21 18:32:33.556294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231c11451996'
down_revision: Union[str, None] = 'b7c9d3e2f158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_connections', sa.Column('granted_scopes', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('channel_connections', sa.Column('account_type', sa.String(length=50), nullable=True))
    op.add_column('channel_connections', sa.Column('token_encrypted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('channel_connections', sa.Column('refresh_supported', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('channel_connections', sa.Column('last_refresh_at', sa.DateTime(), nullable=True))
    op.add_column('channel_connections', sa.Column('last_health_check_at', sa.DateTime(), nullable=True))
    op.add_column('channel_connections', sa.Column('last_health_status', sa.String(length=20), nullable=True))
    op.add_column('channel_connections', sa.Column('disconnect_reason', sa.String(length=255), nullable=True))
    op.add_column('channel_connections', sa.Column('capabilities', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('global_pattern_stats', sa.Column('source_cohort_id', sa.Uuid(), nullable=True))
    op.add_column('global_pattern_stats', sa.Column('category', sa.String(length=50), nullable=False, server_default='general'))
    op.create_foreign_key(op.f('fk_global_pattern_stats_source_cohort_id_cohort_definitions'), 'global_pattern_stats', 'cohort_definitions', ['source_cohort_id'], ['id'])
    op.add_column('tenant_patterns', sa.Column('decay_weighted_reward', sa.Float(), nullable=True))
    op.add_column('tenant_patterns', sa.Column('sample_count_decayed', sa.Float(), nullable=True))
    op.add_column('tenant_patterns', sa.Column('evidence', sa.JSON(), nullable=True))
    op.add_column('tenant_patterns', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tenant_patterns', sa.Column('pinned_by', sa.Uuid(), nullable=True))
    op.add_column('tenant_patterns', sa.Column('pinned_at', sa.DateTime(), nullable=True))
    op.add_column('tenant_patterns', sa.Column('direction', sa.String(length=10), nullable=False, server_default='positive'))
    op.create_foreign_key(op.f('fk_tenant_patterns_pinned_by_users'), 'tenant_patterns', 'users', ['pinned_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tenant_patterns_pinned_by_users'), 'tenant_patterns', type_='foreignkey')
    op.drop_column('tenant_patterns', 'direction')
    op.drop_column('tenant_patterns', 'pinned_at')
    op.drop_column('tenant_patterns', 'pinned_by')
    op.drop_column('tenant_patterns', 'is_pinned')
    op.drop_column('tenant_patterns', 'evidence')
    op.drop_column('tenant_patterns', 'sample_count_decayed')
    op.drop_column('tenant_patterns', 'decay_weighted_reward')
    op.drop_constraint(op.f('fk_global_pattern_stats_source_cohort_id_cohort_definitions'), 'global_pattern_stats', type_='foreignkey')
    op.drop_column('global_pattern_stats', 'category')
    op.drop_column('global_pattern_stats', 'source_cohort_id')
    op.drop_column('channel_connections', 'capabilities')
    op.drop_column('channel_connections', 'disconnect_reason')
    op.drop_column('channel_connections', 'last_health_status')
    op.drop_column('channel_connections', 'last_health_check_at')
    op.drop_column('channel_connections', 'last_refresh_at')
    op.drop_column('channel_connections', 'refresh_supported')
    op.drop_column('channel_connections', 'token_encrypted')
    op.drop_column('channel_connections', 'account_type')
    op.drop_column('channel_connections', 'granted_scopes')
    # ### end Alembic commands ###
