"""initial schema

Revision ID: 64ece5c29775
Revises: 
Create Date: 2026-03-19 12:35:44.781874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ece5c29775'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('price_yearly', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_billing_plans_name')),
    sa.UniqueConstraint('tier', name=op.f('uq_billing_plans_tier'))
    )
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('artists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('spotify_id', sa.String(length=100), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_artists_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists')),
    sa.UniqueConstraint('tenant_id', 'slug', name=op.f('uq_artists_tenant_id'))
    )
    op.create_index(op.f('ix_artists_tenant_id'), 'artists', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_tenant_action_created', 'audit_logs', ['tenant_id', 'action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('campaign_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('post_templates', sa.JSON(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_campaign_templates_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_templates'))
    )
    op.create_index('ix_campaign_templates_global', 'campaign_templates', ['is_global', 'is_active'], unique=False)
    op.create_index(op.f('ix_campaign_templates_tenant_id'), 'campaign_templates', ['tenant_id'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_daily_metrics_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_metrics')),
    sa.UniqueConstraint('tenant_id', 'source', 'metric_name', 'entity_type', 'entity_id', 'date', name=op.f('uq_daily_metrics_tenant_id'))
    )
    op.create_index(op.f('ix_daily_metrics_tenant_id'), 'daily_metrics', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_memberships_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'tenant_id', name=op.f('uq_memberships_user_id'))
    )
    op.create_table('metric_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_metric_events_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_events'))
    )
    op.create_index(op.f('ix_metric_events_tenant_id'), 'metric_events', ['tenant_id'], unique=False)
    op.create_index('ix_metric_events_tenant_source_type_occurred', 'metric_events', ['tenant_id', 'source', 'event_type', 'occurred_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.Date(), nullable=False),
    sa.Column('current_period_end', sa.Date(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], name=op.f('fk_subscriptions_plan_id_billing_plans')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_subscriptions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_subscriptions_tenant_id'))
    )
    op.create_table('channel_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('integration_mode', sa.String(length=20), server_default='automatic', nullable=False),
    sa.Column('platform_account_id', sa.String(length=255), nullable=True),
    sa.Column('platform_url', sa.String(length=500), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_channel_connections_artist_id_artists')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_channel_connections_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_connections'))
    )
    op.create_index(op.f('ix_channel_connections_tenant_id'), 'channel_connections', ['tenant_id'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('release_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('upc', sa.String(length=20), nullable=True),
    sa.Column('artwork_url', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('hyperfollow_url', sa.String(length=500), nullable=True),
    sa.Column('linktree_url', sa.String(length=500), nullable=True),
    sa.Column('bandcamp_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('tiktok_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_releases_artist_id_artists')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_releases_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_releases'))
    )
    op.create_index(op.f('ix_releases_tenant_id'), 'releases', ['tenant_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_campaigns_artist_id_artists')),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_campaigns_release_id_releases')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_campaigns_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('isrc', sa.String(length=20), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('is_single', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_tracks_release_id_releases')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tracks_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks'))
    )
    op.create_index(op.f('ix_tracks_tenant_id'), 'tracks', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_assets_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_assets_release_id_releases')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_assets_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('assisted_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('url_validations', sa.JSON(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_assisted_tasks_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['channel_id'], ['channel_connections.id'], name=op.f('fk_assisted_tasks_channel_id_channel_connections')),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_assisted_tasks_release_id_releases')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_assisted_tasks_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assisted_tasks'))
    )
    op.create_index(op.f('ix_assisted_tasks_tenant_id'), 'assisted_tasks', ['tenant_id'], unique=False)
    op.create_index('ix_assisted_tasks_tenant_platform', 'assisted_tasks', ['tenant_id', 'platform'], unique=False)
    op.create_index('ix_assisted_tasks_tenant_status', 'assisted_tasks', ['tenant_id', 'status'], unique=False)
    op.create_table('calendar_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_calendar_items_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_calendar_items_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_items'))
    )
    op.create_index(op.f('ix_calendar_items_tenant_id'), 'calendar_items', ['tenant_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('cohort_platform', sa.String(length=50), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.Column('winner_variant', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('metrics_config', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_experiments_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_experiments_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_tenant_id'), 'experiments', ['tenant_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('permalink', sa.String(length=500), nullable=True),
    sa.Column('engagement', sa.JSON(), nullable=False),
    sa.Column('destination_url', sa.String(length=500), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('policy_decision', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_posts_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['channel_id'], ['channel_connections.id'], name=op.f('fk_posts_channel_id_channel_connections')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_posts_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index(op.f('ix_posts_tenant_id'), 'posts', ['tenant_id'], unique=False)
    op.create_table('redirects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('target_url', sa.String(length=2000), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_redirects_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_redirects_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redirects'))
    )
    op.create_index(op.f('ix_redirects_slug'), 'redirects', ['slug'], unique=True)
    op.create_index(op.f('ix_redirects_tenant_id'), 'redirects', ['tenant_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_reasons', sa.JSON(), nullable=False),
    sa.Column('policy_snapshot', sa.JSON(), nullable=False),
    sa.Column('action_payload', sa.JSON(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_approvals_asset_id_assets')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_approvals_post_id_posts')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_approvals_requested_by_users')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_approvals_reviewed_by_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_approvals_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index('ix_approvals_tenant_action_type', 'approvals', ['tenant_id', 'action_type'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    op.create_index('ix_approvals_tenant_status', 'approvals', ['tenant_id', 'status'], unique=False)
    op.create_table('asset_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_variants_asset_id_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_variants'))
    )
    op.create_table('approval_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_approval_comments_approval_id_approvals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_approval_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_comments'))
    )
    op.create_index(op.f('ix_approval_comments_approval_id'), 'approval_comments', ['approval_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_comments_approval_id'), table_name='approval_comments')
    op.drop_table('approval_comments')
    op.drop_table('asset_variants')
    op.drop_index('ix_approvals_tenant_status', table_name='approvals')
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index('ix_approvals_tenant_action_type', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_redirects_tenant_id'), table_name='redirects')
    op.drop_index(op.f('ix_redirects_slug'), table_name='redirects')
    op.drop_table('redirects')
    op.drop_index(op.f('ix_posts_tenant_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_experiments_tenant_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_calendar_items_tenant_id'), table_name='calendar_items')
    op.drop_table('calendar_items')
    op.drop_index('ix_assisted_tasks_tenant_status', table_name='assisted_tasks')
    op.drop_index('ix_assisted_tasks_tenant_platform', table_name='assisted_tasks')
    op.drop_index(op.f('ix_assisted_tasks_tenant_id'), table_name='assisted_tasks')
    op.drop_table('assisted_tasks')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_tracks_tenant_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_releases_tenant_id'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_channel_connections_tenant_id'), table_name='channel_connections')
    op.drop_table('channel_connections')
    op.drop_table('subscriptions')
    op.drop_index('ix_metric_events_tenant_source_type_occurred', table_name='metric_events')
    op.drop_index(op.f('ix_metric_events_tenant_id'), table_name='metric_events')
    op.drop_table('metric_events')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_daily_metrics_tenant_id'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_campaign_templates_tenant_id'), table_name='campaign_templates')
    op.drop_index('ix_campaign_templates_global', table_name='campaign_templates')
    op.drop_table('campaign_templates')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_artists_tenant_id'), table_name='artists')
    op.drop_table('artists')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
