"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { Header } from "@/components/layout/header";
import { apiGet, apiPost, apiPut, apiDelete } from "@/lib/api";
import { cn } from "@/lib/utils";
import { LoadingOverlay, ButtonSpinner } from "@/components/ui/spinner";
import { MediaPreview, DownloadAllButton } from "@/components/ui/media-preview";

// Interfaces matching the API response (snake_case from Python)
interface CampaignConfig {
  channels?: string[];
  posts_per_day?: number;
  focus?: string;
  genre?: string;
  content_notes?: string;
}

interface Channel {
  id: string;
  platform: string;
  display_name: string | null;
  is_active: boolean;
  artist_id: string;
}

interface CampaignDetail {
  id: string;
  name: string;
  status: string;
  mode: string;
  phase: string;
  artist_id: string;
  release_id: string | null;
  start_date: string | null;
  end_date: string | null;
  budget: number | null;
  config: CampaignConfig;
  created_at: string;
}

interface PlanPost {
  id: string;
  platform: string;
  status: string;
  content_text: string;
  approval_status: string | null;
  day_number: number | null;
  action_type_label: string | null;
  scheduled_at: string | null;
  destination_url: string | null;
  channel_id: string;
  media_urls: string[];
  created_at: string;
}

interface CalendarItem {
  id: string;
  title: string;
  description: string;
  item_type: string;
  scheduled_date: string;
  scheduled_time: string | null;
  is_completed: boolean;
}

interface PlanDay {
  day: string;
  day_number: number;
  calendar_items: CalendarItem[];
  posts: PlanPost[];
}

interface CampaignPlan {
  campaign: CampaignDetail;
  days: PlanDay[];
  stats: {
    total_posts: number;
    pending_review: number;
    approved: number;
    rejected: number;
    published: number;
  };
}

const approvalColors: Record<string, string> = {
  pending_review: "bg-amber-100 text-amber-700",
  approved: "bg-green-100 text-green-700",
  rejected: "bg-red-100 text-red-700",
};

const platformIcons: Record<string, string> = {
  instagram: "\u{1F4F8}",
  tiktok: "\u{1F3B5}",
  youtube: "\u25B6\uFE0F",
  twitter: "\u{1D54F}",
  facebook: "\u{1F4D8}",
};

const modeLabels: Record<string, { label: string; color: string }> = {
  manual: { label: "Manual", color: "bg-gray-100 text-gray-600" },
  ai_plan: { label: "AI Plan", color: "bg-indigo-100 text-indigo-600" },
  autopilot: { label: "Autopilot", color: "bg-purple-100 text-purple-600" },
};

export default function CampaignDetailPage() {
  const params = useParams();
  const router = useRouter();
  const searchParams = useSearchParams();
  const campaignId = params.id as string;
  const autoGenerate = searchParams.get("generate") === "true";
  const hasAutoGenerated = useRef(false);

  const [plan, setPlan] = useState<CampaignPlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [approvingAll, setApprovingAll] = useState(false);
  const [actioningPost, setActioningPost] = useState<string | null>(null);
  const [editingPost, setEditingPost] = useState<string | null>(null);
  const [editText, setEditText] = useState("");
  const [editMediaUrls, setEditMediaUrls] = useState<string[]>([]);
  const [showAssetPicker, setShowAssetPicker] = useState(false);
  const [availableAssets, setAvailableAssets] = useState<Array<{id: string; name: string; file_url: string; asset_type: string; mime_type?: string}>>([]);
  const [generatingPlan, setGeneratingPlan] = useState(false);
  const [showPlanOptions, setShowPlanOptions] = useState(false);
  const [contentNotes, setContentNotes] = useState("");
  // Media generation (new 3-step workflow)
  const [generatingMedia, setGeneratingMedia] = useState<string | null>(null);
  const [generatingAllMedia, setGeneratingAllMedia] = useState(false);
  const [generateAllProgress, setGenerateAllProgress] = useState<{current: number; total: number} | null>(null);
  // Video tier upgrades
  const [generatingVideo, setGeneratingVideo] = useState<string | null>(null);
  const [showVideoForm, setShowVideoForm] = useState<string | null>(null);
  const [videoLyrics, setVideoLyrics] = useState("");
  const [videoDuration, setVideoDuration] = useState(30);
  const [videoAspect, setVideoAspect] = useState("9:16");
  const [generatingClip, setGeneratingClip] = useState<string | null>(null);
  const [showAIVideoForm, setShowAIVideoForm] = useState<string | null>(null);
  const [aiVideoPrompt, setAiVideoPrompt] = useState("");
  const [aiVideoScenes, setAiVideoScenes] = useState(6);
  const [generatingAIVideo, setGeneratingAIVideo] = useState<string | null>(null);
  const [confirmGenerate, setConfirmGenerate] = useState<{postId: string; cost: number} | null>(null);
  // Campaign strategy editor
  const [channels, setChannels] = useState<Channel[]>([]);
  const [showStrategyEditor, setShowStrategyEditor] = useState(false);
  const [strategyConfig, setStrategyConfig] = useState<CampaignConfig>({});
  const [savingStrategy, setSavingStrategy] = useState(false);

  const fetchPlan = useCallback(async () => {
    try {
      const data = await apiGet<CampaignPlan>(`/api/v1/campaigns/${campaignId}/plan`);
      setPlan(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load plan");
    } finally {
      setLoading(false);
    }
  }, [campaignId]);

  useEffect(() => {
    fetchPlan();
    apiGet<Channel[]>("/api/v1/channels").then(setChannels).catch(() => {});
  }, [fetchPlan]);

  // Sync strategy config when plan loads
  useEffect(() => {
    if (plan?.campaign?.config) {
      setStrategyConfig(plan.campaign.config);
    }
  }, [plan]);

  // Auto-generate is handled after handleGeneratePlan is defined below

  const handleApproveAll = async () => {
    setApprovingAll(true);
    try {
      await apiPost(`/api/v1/campaigns/${campaignId}/approve-all`, {});
      await fetchPlan();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Approve all failed");
    } finally {
      setApprovingAll(false);
    }
  };

  const handleGenerateMedia = async (postId: string) => {
    setGeneratingMedia(postId);
    setError(null);
    try {
      await apiPost(`/api/v1/posts/${postId}/generate-media`, {}, 120000);
      await fetchPlan();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Media generation failed");
    } finally {
      setGeneratingMedia(null);
    }
  };

  const handleGenerateAllMedia = async () => {
    if (!plan) return;
    // Collect all approved posts without media
    const postsToGenerate: string[] = [];
    for (const day of plan.days) {
      for (const post of day.posts) {
        if (post.approval_status === "approved" && (!post.media_urls || post.media_urls.length === 0)) {
          postsToGenerate.push(post.id);
        }
      }
    }
    if (postsToGenerate.length === 0) return;

    setGeneratingAllMedia(true);
    setError(null);
    // Generate one at a time to avoid overloading Render
    for (let i = 0; i < postsToGenerate.length; i++) {
      setGenerateAllProgress({ current: i + 1, total: postsToGenerate.length });
      setGeneratingMedia(postsToGenerate[i]);
      try {
        await apiPost(`/api/v1/posts/${postsToGenerate[i]}/generate-media`, {}, 120000);
      } catch (err) {
        setError(err instanceof Error ? err.message : `Failed generating post ${i + 1}`);
        // Continue to next post even if one fails
      }
    }
    setGeneratingMedia(null);
    setGenerateAllProgress(null);
    setGeneratingAllMedia(false);
    await fetchPlan();
  };

  const handlePostAction = async (postId: string, action: "review-approve" | "review-reject") => {
    setActioningPost(postId);
    try {
      await apiPost(`/api/v1/posts/${postId}/${action}`, {});
      await fetchPlan();
    } catch (err) {
      setError(err instanceof Error ? err.message : `${action} failed`);
    } finally {
      setActioningPost(null);
    }
  };

  const syncCalendar = async () => {
    try {
      await apiPost(`/api/v1/campaigns/${campaignId}/sync-calendar`, {});
    } catch {
      // non-fatal
    }
  };

  const handleSaveEdit = async (postId: string) => {
    setActioningPost(postId);
    try {
      const updates: Record<string, unknown> = { content_text: editText };
      if (editMediaUrls.length > 0) updates.media_urls = editMediaUrls;
      await apiPut(`/api/v1/posts/${postId}`, updates);
      setEditingPost(null);
      setShowAssetPicker(false);
      await syncCalendar();
      await fetchPlan();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Save failed");
    } finally {
      setActioningPost(null);
    }
  };

  const loadAssets = async () => {
    try {
      const assets = await apiGet<Array<{id: string; name: string; file_url: string; asset_type: string; mime_type?: string}>>("/api/v1/assets");
      setAvailableAssets(assets);
    } catch {
      // ignore
    }
  };

  const handleGeneratePlan = async () => {
    setGeneratingPlan(true);
    setShowPlanOptions(false);
    setError(null);
    try {
      await apiPost("/api/v1/ai/generate-plan", {
        campaign_id: campaignId,
        content_notes: contentNotes,
      });
      await fetchPlan();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Plan generation failed");
    } finally {
      setGeneratingPlan(false);
    }
  };

  const handleGenerateVideo = async (postId: string) => {
    setGeneratingVideo(postId);
    setError(null);
    try {
      await apiPost("/api/v1/ai/generate-lyric-video", {
        post_id: postId,
        release_id: plan?.campaign?.release_id || undefined,
        lyrics: videoLyrics,
        duration_seconds: videoDuration,
        aspect_ratio: videoAspect,
        artist_name: "",  // Will be resolved server-side
      });
      setShowVideoForm(null);
      setVideoLyrics("");
      await fetchPlan();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Video generation failed");
    } finally {
      setGeneratingVideo(null);
    }
  };

  const handleRequestAIVideo = async (postId: string) => {
    // Get cost estimate first, then show confirmation
    try {
      const estimate = await apiPost<{estimated_cost: number; num_clips: number}>("/api/v1/ai/estimate-video-cost", {
        num_scenes: aiVideoScenes,
      });
      setConfirmGenerate({ postId, cost: estimate.estimated_cost });
    } catch (_err) {
      setConfirmGenerate({ postId, cost: aiVideoScenes * 0.25 });
    }
  };

  const handleGenerateClip = async (postId: string) => {
    setGeneratingClip(postId);
    setError(null);
    try {
      await apiPost("/api/v1/ai/generate-static-video", {
        post_id: postId,
        duration_seconds: videoDuration,
        aspect_ratio: videoAspect,
      });
      await fetchPlan();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Video clip generation failed");
    } finally {
      setGeneratingClip(null);
    }
  };

  const handleConfirmAIVideo = async () => {
    if (!confirmGenerate) return;
    const postId = confirmGenerate.postId;
    setConfirmGenerate(null);
    setGeneratingAIVideo(postId);
    setError(null);
    try {
      await apiPost("/api/v1/ai/generate-ai-video", {
        post_id: postId,
        prompt: aiVideoPrompt,
        release_id: plan?.campaign?.release_id || undefined,
        aspect_ratio: videoAspect,
        duration_seconds: videoDuration,
        num_scenes: aiVideoScenes,
      });
      setShowAIVideoForm(null);
      setAiVideoPrompt("");
      await fetchPlan();
    } catch (err) {
      setError(err instanceof Error ? err.message : "AI video generation failed");
    } finally {
      setGeneratingAIVideo(null);
    }
  };

  // Auto-generate: instead of firing immediately, show the constraints form
  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current && plan && plan.days.length === 0 && !generatingPlan) {
      hasAutoGenerated.current = true;
      router.replace(`/campaigns/${campaignId}`);
      setShowPlanOptions(true);
    }
  }, [autoGenerate, plan, generatingPlan, campaignId, router]);

  const handleLaunch = async () => {
    try {
      await apiPost(`/api/v1/campaigns/${campaignId}/launch`, {});
      await fetchPlan();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Launch failed");
    }
  };

  const handleSaveStrategy = async () => {
    setSavingStrategy(true);
    setError(null);
    try {
      await apiPut(`/api/v1/campaigns/${campaignId}`, { config: strategyConfig });
      setShowStrategyEditor(false);
      await fetchPlan();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save strategy");
    } finally {
      setSavingStrategy(false);
    }
  };

  const toggleChannel = (channelId: string) => {
    setStrategyConfig(prev => {
      const current = prev.channels || [];
      const next = current.includes(channelId)
        ? current.filter(id => id !== channelId)
        : [...current, channelId];
      return { ...prev, channels: next };
    });
  };

  if (loading) {
    return (
      <>
        <Header title="Campaign" />
        <LoadingOverlay text="Loading campaign plan..." />
      </>
    );
  }

  if (!plan) {
    return (
      <>
        <Header title="Campaign" />
        <div className="mt-8 text-center text-[var(--text-secondary)]">
          Campaign not found.
        </div>
      </>
    );
  }

  const { campaign, days, stats } = plan;
  const modeInfo = modeLabels[campaign.mode] || modeLabels.manual;

  // Count approved posts that still need media generation
  const needsMedia = days.reduce((acc, day) =>
    acc + day.posts.filter(p => p.approval_status === "approved" && (!p.media_urls || p.media_urls.length === 0)).length, 0
  );

  return (
    <>
      <Header title={campaign.name} />

      {/* Back link */}
      <button
        onClick={() => router.push("/campaigns")}
        className="mt-4 text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
      >
        &larr; Back to Campaigns
      </button>

      {error && (
        <div className="mt-4 rounded-lg border border-red-500/30 bg-red-50 px-4 py-3 text-sm text-red-600 flex items-center justify-between">
          <span>{error}</span>
          <button onClick={() => setError(null)} className="text-xs opacity-60 hover:opacity-100">Dismiss</button>
        </div>
      )}

      {/* Campaign Header Card */}
      <div className="mt-6 rounded-xl border border-[var(--border-color)] bg-[var(--bg-surface)] p-5">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <h2 className="text-lg font-semibold text-[var(--text-primary)]">{campaign.name}</h2>
            <span className={cn("rounded-full px-2.5 py-0.5 text-xs font-medium", modeInfo.color)}>
              {modeInfo.label}
            </span>
            <span className={cn(
              "rounded-full px-2.5 py-0.5 text-xs font-medium",
              campaign.status === "active" ? "bg-green-100 text-green-600" :
              campaign.status === "paused" ? "bg-yellow-100 text-yellow-600" :
              campaign.status === "completed" ? "bg-blue-100 text-blue-600" :
              "bg-gray-100 text-gray-500"
            )}>
              {campaign.status}
            </span>
          </div>
          <div className="flex gap-2">
            {campaign.mode !== "manual" && days.length === 0 && (
              <button
                onClick={() => showPlanOptions ? handleGeneratePlan() : setShowPlanOptions(true)}
                disabled={generatingPlan}
                className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:opacity-90 disabled:opacity-50"
              >
                {generatingPlan ? <ButtonSpinner label="Generating..." /> : "Generate AI Plan"}
              </button>
            )}
            {campaign.mode !== "manual" && days.length > 0 && (
              <button
                onClick={() => showPlanOptions ? handleGeneratePlan() : setShowPlanOptions(true)}
                disabled={generatingPlan}
                className="rounded-lg bg-indigo-600/10 px-4 py-2 text-sm font-medium text-indigo-600 hover:bg-indigo-600/20 disabled:opacity-50"
              >
                {generatingPlan ? <ButtonSpinner label="Regenerating..." /> : "Regenerate Plan"}
              </button>
            )}
            {campaign.status === "draft" && (
              <button
                onClick={handleLaunch}
                className="rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:opacity-90"
              >
                Launch Campaign
              </button>
            )}
          </div>
        </div>
        {(campaign.start_date || campaign.end_date) && (
          <p className="mt-2 text-xs text-[var(--text-secondary)]">
            {campaign.start_date && `Starts ${campaign.start_date}`}
            {campaign.end_date && ` \u00B7 Ends ${campaign.end_date}`}
            {campaign.phase && ` \u00B7 ${campaign.phase.replace("_", " ")}`}
          </p>
        )}

        {/* Plan generation options */}
        {showPlanOptions && !generatingPlan && (
          <div className="mt-3 rounded-lg border border-indigo-200 bg-indigo-50/50 p-4 space-y-3">
            <div>
              <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1">
                Content constraints (tell the AI what you have and don&apos;t have)
              </label>
              <textarea
                value={contentNotes}
                onChange={(e) => setContentNotes(e.target.value)}
                placeholder={"Example: AI-generated music — no live footage, no personal photos, no acoustic versions.\nI have album art, track audio files, and promo images.\nFocus on audio snippets, lyric graphics, playlist promotion, and text-based engagement."}
                rows={3}
                className="w-full rounded-lg border border-[var(--border-color)] bg-white px-3 py-2 text-sm text-[var(--text-primary)] placeholder:text-[var(--text-secondary)]"
              />
              <p className="mt-1 text-[10px] text-[var(--text-secondary)]">
                The AI will also check your Asset Library to see what media you have available.
              </p>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleGeneratePlan}
                className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:opacity-90"
              >
                Generate Plan
              </button>
              <button
                onClick={() => setShowPlanOptions(false)}
                className="rounded-lg px-4 py-2 text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)]"
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {/* Strategy Settings Summary / Editor */}
        <div className="mt-3 border-t border-[var(--border-color)] pt-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3 text-xs text-[var(--text-secondary)]">
              <span className="font-medium text-[var(--text-primary)]">Strategy:</span>
              {strategyConfig.posts_per_day ? (
                <span>{strategyConfig.posts_per_day} posts/day</span>
              ) : (
                <span className="italic">Not configured</span>
              )}
              {strategyConfig.focus && <span>· {strategyConfig.focus}</span>}
              {strategyConfig.genre && <span>· {strategyConfig.genre}</span>}
              {strategyConfig.channels && strategyConfig.channels.length > 0 && (
                <span>· {strategyConfig.channels.length} channel{strategyConfig.channels.length !== 1 ? "s" : ""}</span>
              )}
            </div>
            <button
              onClick={() => setShowStrategyEditor(!showStrategyEditor)}
              className="text-xs font-medium text-indigo-600 hover:text-indigo-700"
            >
              {showStrategyEditor ? "Close" : "Edit Strategy"}
            </button>
          </div>

          {showStrategyEditor && (
            <div className="mt-3 rounded-lg border border-[var(--border-color)] bg-[var(--bg-primary)] p-4 space-y-4">
              {/* Channels */}
              {channels.length > 0 && (
                <div>
                  <label className="block text-xs font-medium text-[var(--text-secondary)] mb-2">Channels to post on</label>
                  <div className="flex flex-wrap gap-2">
                    {channels.filter(ch => ch.is_active).map(ch => {
                      const selected = (strategyConfig.channels || []).includes(ch.id);
                      return (
                        <button
                          key={ch.id}
                          onClick={() => toggleChannel(ch.id)}
                          className={cn(
                            "rounded-lg px-3 py-1.5 text-xs font-medium border transition-colors",
                            selected
                              ? "bg-indigo-600 text-white border-indigo-600"
                              : "bg-white text-[var(--text-secondary)] border-[var(--border-color)] hover:border-indigo-300"
                          )}
                        >
                          {platformIcons[ch.platform] || ""} {ch.display_name || ch.platform}
                        </button>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Posts per day + Focus */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1">Posts per day</label>
                  <select
                    value={strategyConfig.posts_per_day || 2}
                    onChange={(e) => setStrategyConfig(prev => ({ ...prev, posts_per_day: Number(e.target.value) }))}
                    className="w-full rounded-lg border border-[var(--border-color)] bg-white px-3 py-2 text-sm"
                  >
                    <option value={1}>1 post/day</option>
                    <option value={2}>2 posts/day</option>
                    <option value={3}>3 posts/day</option>
                    <option value={4}>4 posts/day</option>
                    <option value={5}>5 posts/day</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1">Focus</label>
                  <select
                    value={strategyConfig.focus || "engagement"}
                    onChange={(e) => setStrategyConfig(prev => ({ ...prev, focus: e.target.value }))}
                    className="w-full rounded-lg border border-[var(--border-color)] bg-white px-3 py-2 text-sm"
                  >
                    <option value="engagement">Engagement</option>
                    <option value="awareness">Awareness</option>
                    <option value="streams">Drive Streams</option>
                    <option value="presave">Pre-save Push</option>
                    <option value="balanced">Balanced</option>
                  </select>
                </div>
              </div>

              {/* Genre */}
              <div>
                <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1">Genre / style</label>
                <input
                  type="text"
                  value={strategyConfig.genre || ""}
                  onChange={(e) => setStrategyConfig(prev => ({ ...prev, genre: e.target.value }))}
                  placeholder="e.g. Country, Indie Rock, Hip-Hop"
                  className="w-full rounded-lg border border-[var(--border-color)] bg-white px-3 py-2 text-sm placeholder:text-[var(--text-secondary)]"
                />
              </div>

              {/* Content notes */}
              <div>
                <label className="block text-xs font-medium text-[var(--text-secondary)] mb-1">Content notes for AI</label>
                <textarea
                  value={strategyConfig.content_notes || ""}
                  onChange={(e) => setStrategyConfig(prev => ({ ...prev, content_notes: e.target.value }))}
                  placeholder="e.g. No live footage available. Focus on album art, audio snippets, lyric posts."
                  rows={2}
                  className="w-full rounded-lg border border-[var(--border-color)] bg-white px-3 py-2 text-sm placeholder:text-[var(--text-secondary)]"
                />
              </div>

              <div className="flex gap-2">
                <button
                  onClick={handleSaveStrategy}
                  disabled={savingStrategy}
                  className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:opacity-90 disabled:opacity-50"
                >
                  {savingStrategy ? <ButtonSpinner label="Saving..." /> : "Save Strategy"}
                </button>
                <button
                  onClick={() => {
                    setStrategyConfig(plan?.campaign?.config || {});
                    setShowStrategyEditor(false);
                  }}
                  className="rounded-lg px-4 py-2 text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)]"
                >
                  Cancel
                </button>
              </div>
              <p className="text-[10px] text-[var(--text-secondary)]">
                These settings guide the AI when generating or regenerating a plan. Save, then click &quot;Regenerate Plan&quot; to apply.
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Stats Bar */}
      {stats.total_posts > 0 && (
        <div className="mt-4 grid grid-cols-6 gap-3">
          {[
            { label: "Total Posts", value: stats.total_posts, color: "text-[var(--text-primary)]" },
            { label: "Pending Review", value: stats.pending_review, color: "text-amber-600" },
            { label: "Needs Media", value: needsMedia, color: "text-indigo-600" },
            { label: "Approved", value: stats.approved, color: "text-green-600" },
            { label: "Rejected", value: stats.rejected, color: "text-red-600" },
            { label: "Published", value: stats.published, color: "text-blue-600" },
          ].map((s) => (
            <div key={s.label} className="rounded-lg border border-[var(--border-color)] bg-[var(--bg-surface)] p-3 text-center">
              <div className={cn("text-2xl font-bold", s.color)}>{s.value}</div>
              <div className="text-xs text-[var(--text-secondary)]">{s.label}</div>
            </div>
          ))}
        </div>
      )}

      {/* Bulk Actions */}
      {campaign.mode === "ai_plan" && (stats.pending_review > 0 || stats.approved > 0) && (
        <div className="mt-4 flex items-center gap-3 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3">
          {stats.pending_review > 0 && (
            <>
              <span className="text-sm text-amber-700">
                {stats.pending_review} post{stats.pending_review !== 1 ? "s" : ""} awaiting review
              </span>
              <button
                onClick={handleApproveAll}
                disabled={approvingAll || generatingAllMedia}
                className="rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:opacity-90 disabled:opacity-50"
              >
                {approvingAll ? <ButtonSpinner label="Approving..." /> : "Approve All"}
              </button>
            </>
          )}
          <button
            onClick={handleGenerateAllMedia}
            disabled={generatingAllMedia || approvingAll}
            className="ml-auto rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:opacity-90 disabled:opacity-50"
          >
            {generatingAllMedia && generateAllProgress
              ? <ButtonSpinner label={`Generating ${generateAllProgress.current}/${generateAllProgress.total}...`} />
              : "Generate All Media"}
          </button>
        </div>
      )}

      {/* Empty State */}
      {days.length === 0 && (
        <div className="mt-8 rounded-xl border border-dashed border-[var(--border-color)] bg-[var(--bg-surface)] p-12 text-center">
          <p className="text-[var(--text-secondary)]">
            {campaign.mode === "manual"
              ? "No posts yet. Create posts manually from the Posts page."
              : "No plan generated yet. Click \"Generate AI Plan\" to get started."}
          </p>
        </div>
      )}

      {/* Daily Timeline */}
      <div className="mt-6 space-y-4">
        {days.map((day) => (
          <div key={day.day} className="rounded-xl border border-[var(--border-color)] bg-[var(--bg-surface)] overflow-hidden">
            {/* Day Header */}
            <div className="bg-[var(--bg-primary)] px-5 py-3 border-b border-[var(--border-color)]">
              <div className="flex items-center gap-2">
                <span className="inline-flex items-center justify-center w-7 h-7 rounded-full bg-indigo-100 text-indigo-600 text-xs font-bold">
                  {day.day_number}
                </span>
                <span className="text-sm font-medium text-[var(--text-primary)]">{day.day}</span>
                <span className="text-xs text-[var(--text-secondary)]">
                  {day.posts.length} post{day.posts.length !== 1 ? "s" : ""}
                  {day.calendar_items.length > 0 && ` \u00B7 ${day.calendar_items.length} task${day.calendar_items.length !== 1 ? "s" : ""}`}
                </span>
              </div>
            </div>

            {/* Calendar Items */}
            {day.calendar_items.length > 0 && (
              <div className="px-5 py-2 border-b border-[var(--border-color)] bg-slate-50/50">
                {day.calendar_items.map((item) => (
                  <div key={item.id} className="flex items-center gap-2 py-1.5 text-xs text-[var(--text-secondary)]">
                    <span className="text-[10px]">{"\u{1F4CB}"}</span>
                    <span>{item.title}</span>
                    {item.scheduled_time && <span className="opacity-50">{item.scheduled_time}</span>}
                  </div>
                ))}
              </div>
            )}

            {/* Posts */}
            <div className="divide-y divide-[var(--border-color)]">
              {day.posts.map((post) => {
                const isEditing = editingPost === post.id;
                const isActioning = actioningPost === post.id;

                return (
                  <div key={post.id} className="px-5 py-4">
                    <div className="flex items-start gap-3">
                      {/* Platform Icon */}
                      <span className="text-lg mt-0.5">{platformIcons[post.platform] || "\u{1F4DD}"}</span>

                      {/* Content */}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1.5">
                          <span className="text-xs font-medium text-[var(--text-primary)] capitalize">{post.platform}</span>
                          {post.action_type_label && (
                            <span className="rounded bg-[var(--bg-primary)] px-1.5 py-0.5 text-[10px] text-[var(--text-secondary)]">
                              {post.action_type_label}
                            </span>
                          )}
                          {post.approval_status && (
                            <span className={cn(
                              "rounded-full px-2 py-0.5 text-[10px] font-medium",
                              approvalColors[post.approval_status] || "bg-gray-100 text-gray-500"
                            )}>
                              {post.approval_status === "pending_review" ? "Pending Review" :
                               post.approval_status === "approved" ? "Approved" : "Rejected"}
                            </span>
                          )}
                        </div>

                        {isEditing ? (
                          <div className="space-y-3">
                            {/* Caption editor */}
                            <div>
                              <label className="block text-[10px] font-medium text-[var(--text-secondary)] mb-1">Caption</label>
                              <textarea
                                value={editText}
                                onChange={(e) => setEditText(e.target.value)}
                                rows={4}
                                className="w-full rounded-lg border border-[var(--border-color)] bg-[var(--bg-primary)] px-3 py-2 text-sm text-[var(--text-primary)] focus:border-indigo-500 focus:outline-none resize-none"
                              />
                            </div>

                            {/* Current media + swap controls */}
                            <div>
                              <div className="flex items-center justify-between mb-1">
                                <label className="text-[10px] font-medium text-[var(--text-secondary)]">
                                  Media ({editMediaUrls.length} file{editMediaUrls.length !== 1 ? "s" : ""})
                                </label>
                                <button
                                  type="button"
                                  onClick={() => { if (!showAssetPicker) loadAssets(); setShowAssetPicker(!showAssetPicker); }}
                                  className="text-[10px] font-medium text-indigo-600 hover:text-indigo-700"
                                >
                                  {showAssetPicker ? "Close Library" : "Swap from Library"}
                                </button>
                              </div>
                              {editMediaUrls.length > 0 && (
                                <div className="flex gap-2 flex-wrap">
                                  {editMediaUrls.map((url, i) => {
                                    const isVideo = /\.(mp4|mov|webm)/i.test(url);
                                    const isAudio = /\.(mp3|wav|aac|flac)/i.test(url);
                                    return (
                                      <div key={i} className="relative group">
                                        {isVideo ? (
                                          <video src={url} className="w-16 h-16 rounded object-cover" muted />
                                        ) : isAudio ? (
                                          <div className="w-16 h-16 rounded bg-gray-100 flex items-center justify-center text-[10px] text-[var(--text-secondary)]">Audio</div>
                                        ) : (
                                          <img src={url} alt="" className="w-16 h-16 rounded object-cover" />
                                        )}
                                        <button
                                          type="button"
                                          onClick={() => setEditMediaUrls(prev => prev.filter((_, idx) => idx !== i))}
                                          className="absolute -top-2 -right-2 w-5 h-5 rounded-full bg-red-500 text-white text-[10px] font-bold flex items-center justify-center shadow-sm"
                                        >
                                          X
                                        </button>
                                      </div>
                                    );
                                  })}
                                </div>
                              )}
                              {/* Asset library picker */}
                              {showAssetPicker && (
                                <div className="mt-2 max-h-48 overflow-y-auto rounded-lg border border-[var(--border-color)] bg-[var(--bg-primary)] p-2">
                                  {availableAssets.length === 0 ? (
                                    <p className="text-xs text-[var(--text-secondary)] text-center py-4">No assets found</p>
                                  ) : (
                                    <div className="grid grid-cols-6 gap-2">
                                      {availableAssets.map(asset => {
                                        const selected = editMediaUrls.includes(asset.file_url);
                                        const isAudio = asset.asset_type === "audio" || /\.(mp3|wav|aac|flac)/i.test(asset.file_url);
                                        const isVideo = asset.asset_type === "video" || /\.(mp4|mov|webm)/i.test(asset.file_url);
                                        return (
                                          <button
                                            key={asset.id}
                                            type="button"
                                            onClick={() => {
                                              if (selected) {
                                                setEditMediaUrls(prev => prev.filter(u => u !== asset.file_url));
                                              } else {
                                                setEditMediaUrls(prev => [...prev, asset.file_url]);
                                              }
                                            }}
                                            className={cn(
                                              "rounded-lg border-2 p-0.5 transition-colors",
                                              selected ? "border-indigo-600" : "border-transparent hover:border-gray-300"
                                            )}
                                            title={asset.name}
                                          >
                                            {isAudio ? (
                                              <div className="w-full aspect-square rounded bg-gray-100 flex flex-col items-center justify-center">
                                                <span className="text-lg">♫</span>
                                                <span className="text-[8px] text-[var(--text-secondary)] truncate w-full px-0.5 text-center">{asset.name}</span>
                                              </div>
                                            ) : isVideo ? (
                                              <div className="w-full aspect-square rounded bg-gray-100 flex flex-col items-center justify-center">
                                                <span className="text-lg">▶</span>
                                                <span className="text-[8px] text-[var(--text-secondary)] truncate w-full px-0.5 text-center">{asset.name}</span>
                                              </div>
                                            ) : (
                                              <img src={asset.file_url} alt={asset.name} className="w-full aspect-square rounded object-cover" />
                                            )}
                                          </button>
                                        );
                                      })}
                                    </div>
                                  )}
                                </div>
                              )}
                            </div>

                            <div className="flex gap-2">
                              <button
                                onClick={() => handleSaveEdit(post.id)}
                                disabled={isActioning}
                                className="rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-medium text-white hover:opacity-90 disabled:opacity-50"
                              >
                                {isActioning ? <ButtonSpinner label="Saving..." /> : "Save"}
                              </button>
                              <button
                                onClick={() => { setEditingPost(null); setShowAssetPicker(false); }}
                                className="rounded-lg px-3 py-1.5 text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)]"
                              >
                                Cancel
                              </button>
                            </div>
                          </div>
                        ) : (
                          <div className="text-sm text-[var(--text-secondary)] whitespace-pre-line">
                            {post.content_text}
                          </div>
                        )}

                        {/* Media Preview + Download */}
                        {post.media_urls && post.media_urls.length > 0 && (
                          <div className="mt-3">
                            {post.media_urls.length > 1 && (
                              <div className="text-[10px] font-medium text-indigo-600 mb-1">
                                {post.media_urls.length} media items
                              </div>
                            )}
                            <MediaPreview urls={post.media_urls} compact />
                            <div className="mt-1">
                              <DownloadAllButton urls={post.media_urls} />
                            </div>
                          </div>
                        )}
                        {/* No media indicator */}
                        {(!post.media_urls || post.media_urls.length === 0) && post.action_type_label !== "live" && (
                          <div className="mt-2 text-[10px] text-[var(--text-secondary)] italic">
                            {post.approval_status === "approved"
                              ? "No media yet — click \"Generate Media\" to find assets and create preview"
                              : "No media — approve this post first, then generate media"}
                          </div>
                        )}

                        {post.destination_url && (
                          <p className="mt-1 text-xs text-indigo-500 truncate">{"\u{1F517}"} {post.destination_url}</p>
                        )}
                      </div>

                      {/* Actions */}
                      {!isEditing && (
                        <div className="flex flex-col gap-1.5 shrink-0 items-end">
                          {/* Step 1: Approval actions */}
                          {post.approval_status === "pending_review" && (
                            <div className="flex gap-1.5">
                              <button
                                onClick={() => handlePostAction(post.id, "review-approve")}
                                disabled={isActioning}
                                className="rounded-lg bg-green-600 px-3 py-1.5 text-xs font-medium text-white hover:opacity-90 disabled:opacity-50"
                                title="Approve post"
                              >
                                {isActioning ? "..." : "\u2713 Approve"}
                              </button>
                              <button
                                onClick={() => handlePostAction(post.id, "review-reject")}
                                disabled={isActioning}
                                className="rounded-lg bg-red-50 px-3 py-1.5 text-xs font-medium text-red-600 hover:bg-red-100 disabled:opacity-50"
                              >
                                {"\u2715"}
                              </button>
                            </div>
                          )}

                          {/* Edit + Delete — available on all non-published posts */}
                          {post.status !== "published" && (
                            <div className="flex gap-1.5">
                              <button
                                onClick={() => {
                                  setEditingPost(post.id);
                                  setEditText(post.content_text);
                                  setEditMediaUrls(post.media_urls || []);
                                  setShowAssetPicker(false);
                                }}
                                className="rounded-lg bg-[var(--bg-primary)] px-2 py-1 text-[10px] font-medium text-[var(--text-secondary)] hover:text-[var(--text-primary)] border border-[var(--border-color)]"
                              >
                                Edit
                              </button>
                              <button
                                onClick={async () => {
                                  if (!confirm("Delete this post?")) return;
                                  setActioningPost(post.id);
                                  try {
                                    await apiDelete(`/api/v1/posts/${post.id}`);
                                    await syncCalendar();
                                    await fetchPlan();
                                  } catch (err) {
                                    setError(err instanceof Error ? err.message : "Delete failed");
                                  } finally {
                                    setActioningPost(null);
                                  }
                                }}
                                disabled={isActioning}
                                className="rounded-lg bg-red-50 px-2 py-1 text-[10px] font-medium text-red-600 hover:bg-red-100 disabled:opacity-50"
                              >
                                Delete
                              </button>
                            </div>
                          )}

                          {/* Generate / Regenerate media (approved posts) */}
                          {post.approval_status === "approved" && post.status !== "published" && (
                            <button
                              onClick={() => handleGenerateMedia(post.id)}
                              disabled={generatingMedia === post.id || generatingAllMedia}
                              className={cn(
                                "rounded-lg px-3 py-1.5 text-xs font-medium hover:opacity-90 disabled:opacity-50",
                                post.media_urls && post.media_urls.length > 0
                                  ? "bg-indigo-100 text-indigo-700 border border-indigo-300"
                                  : "bg-indigo-600 text-white"
                              )}
                              title={post.media_urls && post.media_urls.length > 0 ? "Re-match assets from library" : "Generate media from asset library"}
                            >
                              {generatingMedia === post.id ? <ButtonSpinner label="Generating..." /> :
                                post.media_urls && post.media_urls.length > 0 ? "Regenerate Media" : "Generate Media"}
                            </button>
                          )}

                          {/* Step 3: Schedule (approved posts WITH media, not yet scheduled/published) */}
                          {post.approval_status === "approved" && post.media_urls && post.media_urls.length > 0 && !["scheduled", "publishing", "published"].includes(post.status) && (
                            <button
                              onClick={async () => {
                                setActioningPost(post.id);
                                try {
                                  const scheduleAt = post.scheduled_at || new Date().toISOString();
                                  await apiPost(`/api/v1/posts/${post.id}/schedule`, { scheduled_at: scheduleAt });
                                  await fetchPlan();
                                } catch (err) {
                                  setError(err instanceof Error ? err.message : "Schedule failed");
                                } finally {
                                  setActioningPost(null);
                                }
                              }}
                              disabled={isActioning}
                              className="rounded-lg bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:opacity-90 disabled:opacity-50"
                            >
                              {isActioning ? "..." : post.scheduled_at ? `Schedule (${new Date(post.scheduled_at).toLocaleDateString()})` : "Schedule Now"}
                            </button>
                          )}

                          {post.status === "scheduled" && (
                            <span className="text-blue-500 text-xs font-medium">Scheduled</span>
                          )}
                          {post.status === "published" && (
                            <span className="text-green-500 text-xs font-medium">Published</span>
                          )}
                          {(post.status === "publishing" || post.status === "failed") && (
                            <div className="flex flex-col items-end gap-1.5">
                              <span className="text-amber-500 text-xs font-medium">
                                {post.status === "publishing" ? "Stuck publishing" : "Failed"}
                              </span>
                              <div className="flex gap-1.5">
                                <button
                                  onClick={async () => {
                                    setActioningPost(post.id);
                                    try {
                                      await apiPost(`/api/v1/posts/${post.id}/retry`, { republish: true });
                                      await syncCalendar();
                                      await fetchPlan();
                                    } catch (err) {
                                      setError(err instanceof Error ? err.message : "Re-publish failed");
                                    } finally {
                                      setActioningPost(null);
                                    }
                                  }}
                                  disabled={isActioning}
                                  className="rounded-lg bg-green-600 px-3 py-1.5 text-xs font-medium text-white hover:opacity-90 disabled:opacity-50"
                                >
                                  {isActioning ? "..." : "Re-publish Now"}
                                </button>
                                <button
                                  onClick={async () => {
                                    setActioningPost(post.id);
                                    try {
                                      await apiPost(`/api/v1/posts/${post.id}/retry`, {});
                                      await syncCalendar();
                                      await fetchPlan();
                                    } catch (err) {
                                      setError(err instanceof Error ? err.message : "Reset failed");
                                    } finally {
                                      setActioningPost(null);
                                    }
                                  }}
                                  disabled={isActioning}
                                  className="rounded-lg bg-amber-500 px-2 py-1.5 text-xs font-medium text-white hover:opacity-90 disabled:opacity-50"
                                >
                                  Reset
                                </button>
                                <button
                                  onClick={async () => {
                                    if (!confirm("Delete this post?")) return;
                                    setActioningPost(post.id);
                                    try {
                                      await apiDelete(`/api/v1/posts/${post.id}`);
                                      await syncCalendar();
                                      await fetchPlan();
                                    } catch (err) {
                                      setError(err instanceof Error ? err.message : "Delete failed");
                                    } finally {
                                      setActioningPost(null);
                                    }
                                  }}
                                  disabled={isActioning}
                                  className="rounded-lg bg-red-50 px-2 py-1.5 text-xs font-medium text-red-600 hover:bg-red-100 disabled:opacity-50"
                                >
                                  Delete
                                </button>
                                <button
                                  onClick={async () => {
                                    setActioningPost(post.id);
                                    try {
                                      await apiPut(`/api/v1/posts/${post.id}`, { status: "published", published_at: new Date().toISOString() });
                                      await syncCalendar();
                                      await fetchPlan();
                                    } catch (err) {
                                      setError(err instanceof Error ? err.message : "Mark published failed");
                                    } finally {
                                      setActioningPost(null);
                                    }
                                  }}
                                  disabled={isActioning}
                                  className="rounded-lg bg-emerald-50 px-2 py-1.5 text-xs font-medium text-emerald-600 hover:bg-emerald-100 disabled:opacity-50"
                                >
                                  Mark Published
                                </button>
                              </div>
                            </div>
                          )}
                          {post.approval_status === "rejected" && (
                            <span className="text-red-400 text-xs">{"\u2715"} Rejected</span>
                          )}

                          {/* Video upgrade buttons — available on approved posts with media */}
                          {post.approval_status === "approved" && post.media_urls && post.media_urls.length > 0 && (
                            <div className="flex gap-1 flex-wrap justify-end">
                              <button
                                onClick={() => {
                                  setVideoAspect(post.platform === "youtube" ? "16:9" : "9:16");
                                  handleGenerateClip(post.id);
                                }}
                                disabled={generatingClip === post.id}
                                className="rounded-lg bg-indigo-50 px-2 py-1 text-[10px] font-medium text-indigo-600 hover:bg-indigo-100 disabled:opacity-50"
                                title="Replace with video clip (image + audio)"
                              >
                                {generatingClip === post.id ? <ButtonSpinner label="..." /> : "\u{1F3AC} Video Clip"}
                              </button>
                              <button
                                onClick={() => {
                                  setShowVideoForm(showVideoForm === post.id ? null : post.id);
                                  setVideoLyrics("");
                                  setVideoAspect(post.platform === "youtube" ? "16:9" : "9:16");
                                }}
                                disabled={generatingVideo === post.id}
                                className="rounded-lg bg-purple-50 px-2 py-1 text-[10px] font-medium text-purple-600 hover:bg-purple-100 disabled:opacity-50"
                                title="Replace with lyric video"
                              >
                                {generatingVideo === post.id ? <ButtonSpinner label="..." /> : "\u{1F3B6} Lyric Video"}
                              </button>
                              <button
                                onClick={() => {
                                  setShowAIVideoForm(showAIVideoForm === post.id ? null : post.id);
                                  setAiVideoPrompt("");
                                  setVideoAspect(post.platform === "youtube" ? "16:9" : "9:16");
                                }}
                                disabled={generatingAIVideo === post.id}
                                className="rounded-lg bg-pink-50 px-2 py-1 text-[10px] font-medium text-pink-600 hover:bg-pink-100 disabled:opacity-50"
                                title="Replace with AI video (paid)"
                              >
                                {generatingAIVideo === post.id ? <ButtonSpinner label="..." /> : "\u2728 AI Video"}
                              </button>
                            </div>
                          )}
                        </div>
                      )}
                    </div>

                    {/* Lyric Video Generator Form */}
                    {showVideoForm === post.id && (
                      <div className="mt-3 rounded-lg border border-purple-200 bg-purple-50/50 p-3 space-y-2">
                        <p className="text-xs font-medium text-purple-700">Generate Lyric Video</p>
                        <p className="text-[10px] text-purple-600">Lyrics, audio, and image are auto-pulled from the matching track. Override lyrics below if needed.</p>
                        <textarea
                          value={videoLyrics}
                          onChange={(e) => setVideoLyrics(e.target.value)}
                          placeholder="Optional — leave blank to auto-pull lyrics from track"
                          rows={3}
                          className="w-full rounded-lg border border-[var(--border-color)] bg-white px-3 py-2 text-xs text-[var(--text-primary)] placeholder:text-[var(--text-secondary)]"
                        />
                        <div className="flex gap-3 items-center">
                          <div>
                            <label className="text-[10px] text-[var(--text-secondary)]">Duration</label>
                            <select
                              value={videoDuration}
                              onChange={(e) => setVideoDuration(Number(e.target.value))}
                              className="ml-1 rounded border border-[var(--border-color)] bg-white px-2 py-1 text-xs"
                            >
                              <option value={15}>15s</option>
                              <option value={30}>30s</option>
                              <option value={60}>60s</option>
                            </select>
                          </div>
                          <div>
                            <label className="text-[10px] text-[var(--text-secondary)]">Aspect</label>
                            <select
                              value={videoAspect}
                              onChange={(e) => setVideoAspect(e.target.value)}
                              className="ml-1 rounded border border-[var(--border-color)] bg-white px-2 py-1 text-xs"
                            >
                              <option value="9:16">9:16 (Reel/TikTok)</option>
                              <option value="1:1">1:1 (Feed)</option>
                              <option value="16:9">16:9 (YouTube)</option>
                            </select>
                          </div>
                        </div>
                        <div className="flex gap-2">
                          <button
                            onClick={() => handleGenerateVideo(post.id)}
                            disabled={generatingVideo === post.id}
                            className="rounded-lg bg-purple-600 px-3 py-1.5 text-xs font-medium text-white hover:opacity-90 disabled:opacity-50"
                          >
                            {generatingVideo === post.id ? <ButtonSpinner label="Generating video..." /> : "Generate Video"}
                          </button>
                          <button
                            onClick={() => setShowVideoForm(null)}
                            className="rounded-lg px-3 py-1.5 text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)]"
                          >
                            Cancel
                          </button>
                        </div>
                        <p className="text-[10px] text-[var(--text-secondary)]">
                          Creates a video with your album art, audio snippet, and animated lyrics overlay. Takes 15-30 seconds.
                        </p>
                      </div>
                    )}

                    {/* AI Video Generator Form */}
                    {showAIVideoForm === post.id && (
                      <div className="mt-3 rounded-lg border border-pink-200 bg-pink-50/50 p-3 space-y-2">
                        <p className="text-xs font-medium text-pink-700">Generate AI Video (Paid)</p>
                        <textarea
                          value={aiVideoPrompt}
                          onChange={(e) => setAiVideoPrompt(e.target.value)}
                          placeholder="Describe the video scene (or leave blank to auto-generate from lyrics)...&#10;Example: Cinematic shots of a country road at sunset, fireflies, old barn, golden light"
                          rows={3}
                          className="w-full rounded-lg border border-[var(--border-color)] bg-white px-3 py-2 text-xs text-[var(--text-primary)] placeholder:text-[var(--text-secondary)]"
                        />
                        <div className="flex gap-3 items-center">
                          <div>
                            <label className="text-[10px] text-[var(--text-secondary)]">Scenes</label>
                            <select
                              value={aiVideoScenes}
                              onChange={(e) => setAiVideoScenes(Number(e.target.value))}
                              className="ml-1 rounded border border-[var(--border-color)] bg-white px-2 py-1 text-xs"
                            >
                              <option value={4}>4 (~$1.00)</option>
                              <option value={6}>6 (~$1.50)</option>
                              <option value={8}>8 (~$2.00)</option>
                            </select>
                          </div>
                          <div>
                            <label className="text-[10px] text-[var(--text-secondary)]">Duration</label>
                            <select
                              value={videoDuration}
                              onChange={(e) => setVideoDuration(Number(e.target.value))}
                              className="ml-1 rounded border border-[var(--border-color)] bg-white px-2 py-1 text-xs"
                            >
                              <option value={15}>15s</option>
                              <option value={30}>30s</option>
                              <option value={60}>60s</option>
                            </select>
                          </div>
                          <div>
                            <label className="text-[10px] text-[var(--text-secondary)]">Aspect</label>
                            <select
                              value={videoAspect}
                              onChange={(e) => setVideoAspect(e.target.value)}
                              className="ml-1 rounded border border-[var(--border-color)] bg-white px-2 py-1 text-xs"
                            >
                              <option value="9:16">9:16 (Reel/TikTok)</option>
                              <option value="1:1">1:1 (Feed)</option>
                              <option value="16:9">16:9 (YouTube)</option>
                            </select>
                          </div>
                        </div>
                        <div className="flex gap-2">
                          <button
                            onClick={() => handleRequestAIVideo(post.id)}
                            disabled={generatingAIVideo === post.id}
                            className="rounded-lg bg-pink-600 px-3 py-1.5 text-xs font-medium text-white hover:opacity-90 disabled:opacity-50"
                          >
                            {generatingAIVideo === post.id ? <ButtonSpinner label="Generating..." /> : "Generate AI Video"}
                          </button>
                          <button
                            onClick={() => setShowAIVideoForm(null)}
                            className="rounded-lg px-3 py-1.5 text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)]"
                          >
                            Cancel
                          </button>
                        </div>
                        <p className="text-[10px] text-[var(--text-secondary)]">
                          Uses AI to generate video clips from your description, synced with your audio. Takes 2-5 minutes.
                          Generated videos require your approval before entering the asset library.
                        </p>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Cost Confirmation Modal */}
      {confirmGenerate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <div className="bg-white rounded-xl shadow-2xl p-6 max-w-md mx-4 space-y-4">
            <h3 className="text-lg font-semibold text-[var(--text-primary)]">Confirm AI Video Generation</h3>
            <div className="space-y-2 text-sm text-[var(--text-secondary)]">
              <p>This will generate <strong>{aiVideoScenes} AI video clips</strong> and stitch them with your audio.</p>
              <div className="rounded-lg bg-amber-50 border border-amber-200 p-3">
                <p className="text-amber-800 font-medium">Estimated cost: <span className="text-lg">{"$" + confirmGenerate.cost.toFixed(2)}</span></p>
                <p className="text-amber-600 text-xs mt-1">Charged to your Replicate account. This cannot be undone.</p>
              </div>
              <p>The generated video will be placed in <strong>Pending Review</strong> in your Asset Library. You must approve it before it can be used in posts.</p>
            </div>
            <div className="flex gap-3 justify-end pt-2">
              <button
                onClick={() => setConfirmGenerate(null)}
                className="rounded-lg px-4 py-2 text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)] border border-[var(--border-color)]"
              >
                Cancel
              </button>
              <button
                onClick={handleConfirmAIVideo}
                className="rounded-lg bg-pink-600 px-4 py-2 text-sm font-medium text-white hover:opacity-90"
              >
                {"Yes, Generate Video ($" + confirmGenerate.cost.toFixed(2) + ")"}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
